name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Lint Backend
        working-directory: ./backend
        run: npm run lint

      - name: Build Backend
        working-directory: ./backend
        run: npm run build

      - name: Build Frontend
        working-directory: ./frontend
        run: npx ng build --configuration production

      # - name: Run Backend Tests
      #   working-directory: ./backend
      #   run: npm test

      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npx ng test --watch=false --browsers=ChromeHeadless
